#!/usr/bin/env bash

name="deploy.zip"

if [ $# -eq 1 ]; then
    name=$1;
fi

rm -rf $name

zip $name *.php .htaccess css/* resources/* scripts/min/* include/* favicons/* dota2sponsor/*

echo "Done creating $name."
